In [62]:
#exercici 1: Crea una funció que donat un Array d’una dimensió. 
import numpy as np
from scipy import stats
import pandas as pd
import math 

a = np.array([6,9,12,15,18,6,12])
print(a)

[ 6  9 12 15 18  6 12]


In [24]:
#Et faci un resum estadístic bàsic de les dades
#Media
def RS(arr):
    if arr.ndim > 1:
        print("Error: El array tiene más de una dimensión.")
    else:
        print("La media es: "+str(arr.mean()))
        print("La mediana es: "+str(np.median(arr)))
        print("La Desviación estándar es: "+str(np.std(arr)))
        print("La Varianza es: "+str(np.var(arr)))
        print("La Moda es: "+str(stats.mode(arr)))
        print("La Correlación es: "+str(np.corrcoef(arr)))
        print("La Covarianza es: "+str(np.cov(arr)))
        print("El número mínimo es: "+str(np.amin(arr)))
        print("El número máximo es: "+str(np.amax(arr)))
        print("El rango es: "+str(np.amax(arr)-np.amin(arr)))

            
#ejemplo1
RS(a)
#ejemplo2 (verifico que me sale error por que tiene más de un array)
b = np.array([[1,2,3],[23,4,3]])
RS(b)

La media es: 11.142857142857142
La mediana es: 12.0
La Desviación estándar es: 4.15515416349971
La Varianza es: 17.26530612244898
La Moda es: ModeResult(mode=array([6]), count=array([2]))
La Correlación es: 1.0
La Covarianza es: 20.142857142857142
El número mínimo es: 6
El número máximo es: 18
El rango es: 12
Error: El array tiene más de una dimensión.


In [5]:
#Entendiento ejercicio 1 (asi con esto : a.ndim saco cuantas dimensiones tiene un array)
dimension = a.ndim

In [6]:
#Entendiento ejercicio 1 Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.
if dimension >1:
    print(error)

In [80]:
#Entendiento ejercicio 1 
#Mediana
np.median(a) 

12.0

In [81]:
#Entendiento ejercicio 1 
# Desviación estandar
np.std(a)

4.15515416349971

In [82]:
#Entendiento ejercicio 1 
# Varianza
np.var(a) 

17.26530612244898

In [83]:
#Entendiento ejercicio 1
# moda opcion a
stats.mode(a)

ModeResult(mode=array([6]), count=array([2]))

In [84]:
#Entendiento ejercicio 1
#Moda opción b
from statistics import mode, multimode
print(mode(a))
print(multimode(a))

6
[6, 12]


In [86]:
#Entendiento ejercicio 1
# correlacion
np.corrcoef(a)

1.0

In [87]:
#Entendiento ejercicio 1
# covarianza
np.cov(a)

array(20.14285714)

In [88]:
#Entendiento ejercicio 1
#rango 
print(np.amin(a)) #el numero minimo
mini = np.amin(a)
print(np.amax(a)) #el numero maximo
maxi = np.amax(a)
print(maxi - mini) #el rango

6
18
12


In [95]:
#Entendiento ejercicio 1: forma de hacer resumen estadistico rápido
# resumen estadistadistico con pandas
dataframe = pd.DataFrame(a, index=['a', 'b', 'c', 'd', 'e', 'f', 'g'])
dataframe

0
a   6
b   9
c  12
d  15
e  18
f   6
g  12

In [98]:
# resumen estadistadistico con pandas
dataframe.describe()

0
count   7.000000
mean   11.142857
std     4.488079
min     6.000000
25%     7.500000
50%    12.000000
75%    13.500000
max    18.000000

In [34]:
#exercici 2 Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100

def NXN(f):
    print(np.random.randint(100, size=(f, f)))
NXN(3)

[[10 68 64]
 [10 91  4]
 [15  7 72]]


In [89]:
#Entendiendo exercici 2: Crea un quadrat NxN de nombres aleatoris entre el 0 i el 100
x = np.random.randint(100, size=(2, 2))
print(x)

[[34 97]
 [37 27]]


In [60]:
#exercici 3 Crea una funció que donada una taula de dues dimensions (NxM), et calculi els totals per fila i els totals per columna
def NXM(z,m):
    carr = np.random.randint(100, size=(z, m))
    print(carr)
    return carr
    
s = NXM(3,2)
print(s)

[[97 11]
 [70 15]
 [87 87]]
[[97 11]
 [70 15]
 [87 87]]


In [61]:
#exercici 3 Crea una funció que donada una taula de dues dimensions (NxM), et calculi els totals per fila i els totals
def TXF(d):
    print("El total por fila es "+str(np.sum(d, axis = 0)))  
    print("El total por columna es "+str(np.sum(d, axis = 1)))


TXF(s)

El total por fila es [254 113]
El total por columna es [108  85 174]


In [52]:
#entendiendo exercici 3: como  calcular els totals per fila i els totals per columna.
s = np.sum(y, axis=0)
print(s)

[131 151  70]


In [53]:
#exercici 3: et calculi els totals per columna.
s = np.sum(y, axis=1)
print(s)

[174 178]


In [59]:
#exercici 4 Implementa manualment (una funció) que calculi el coeficient de correlació. Informate sobre els seus usos i interpretació.

c = np.array([150,175,166])
d = np.array([58,70,65])

print(" ")
c.mean()
print("media de c")
print(c.mean())

print(" ")
d.mean()
print("media de d")
print(d.mean())

print(" ") 
print("numerador") 
numerador = 0
for i in range(c.size):
    numerador += (c[i]-c.mean()) * (d[i]-d.mean())
print(numerador)

print(" ") 
print("denominador a") 
denominador_a = 0
for i in range(c.size):
    denominador_a += (c[i]-c.mean())**2
print(denominador_a)

print(" ") 
print("denominador b") 
denominador_b = 0
for i in range(c.size):
    denominador_b += (d[i]-d.mean())**2
print(denominador_b)

print(" ")
print("denominador sin raiz")
print(denominador_a*denominador_b)

print(" ")
print ("denominador con raíz")

import math 
print(math.sqrt((denominador_a*denominador_b)))

e = (math.sqrt((denominador_a*denominador_b)))
d = (numerador)

print(" ")
print ("resultado final coeficiente de correlación")
print(d/e)

 
media de c
163.66666666666666
 
media de d
64.33333333333333
 
numerador
152.33333333333334
 
denominador a
320.6666666666667
 
denominador b
72.66666666666667
 
denominador sin raiz
23301.77777777778
 
denominador con raíz
152.64919841839256
 
resultado final coeficiente de correlación
0.9979307779645624


In [64]:
#exercici 4: Lo estoy intentando arreglar, Implementa manualment una funció que calculi el coeficient de correlació. Informate sobre els seus usos i interpretació.

def CC(g,h):
    print("La media del primer array es "+str(g.mean()))
    print("La media del segundo array es "+str(h.mean()))
    print("El numerador es ") 
    numerador = 0
    for i in range(g.size):
    numerador += (g[i]-g.mean()) * (h[i]-h.mean())
    print(numerador)
    print("denominador a") 
    denominador_a = 0
    for i in range(c.size):
    denominador_a += (c[i]-c.mean())**2
    print(denominador_a)
    print("denominador b") 
    denominador_b = 0
    for i in range(g.size):
    denominador_b += (h[i]-h.mean())**2
    print(denominador_b)
    print("denominador sin raiz"+str(denominador_a*denominador_b))
    print ("denominador con raíz")
    print(math.sqrt((denominador_a*denominador_b)))
    e = (math.sqrt((denominador_a*denominador_b)))
    d = (numerador)
    print("El coeficiente de correlación es "+str((d/e))  
   




IndentationError: expected an indented block (871293304.py, line 7)